#!/usr/bin/env python3
# author: daniel rode
# dependencies: podman, hunspell, gm
# updated: -


import os
import sys
import subprocess as sp
from pathlib import Path
from tempfile import TemporaryDirectory
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures import as_completed
from collections.abc import Iterator
from collections.abc import Callable
from typing import Any


# Functions
def cd0() -> None:
    """Set working directory to the same location as the running script."""

    os.chdir(Path(__file__).resolve().parent)

def print2(*a, **kw):
    print(*a, **kw, file=sys.stderr)

def dispatch(
    jobs: iter, worker: Callable, max_workers=os.cpu_count(),
) -> Iterator[(Any, Any)]:
    """Run jobs in parallel.

    Parallel apply dispatching function: Run a list of jobs with a given
    worker function, in parallel. Yield worker results in order they
    finish.
    """

    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures_jobs = {executor.submit(worker, j): j for j in jobs}
        for f in as_completed(futures_jobs):
            yield (futures_jobs[f], f.result())

def podman(con_args, img, entry_args, sp_args):
    cmd = (
        "podman",
        "run",
        "--rm",
        "--interactive",
        "--volume=./:/portal",
        "--workdir=/portal",
        *con_args,
        img,
        *entry_args,
    )
    return sp.run(cmd, text=True, **sp_args)

def typst(
    *args,
    podman_args=[],
    sp_args={'capture_output': True},
) -> str:
    p = podman(
        con_args=(
            "--entrypoint=typst",
            *podman_args,
        ),
        img="docker.io/pandoc/typst:latest",
        entry_args=args,
        sp_args=sp_args,
    )

    if p.stderr:
        print2(p.stderr)
    if p.returncode != 0:
        print2("error: Typst:", p)

    return p.stdout

def pandoc(
    *args,
    podman_args=[],
    sp_args={'check': True},
) -> None:
    podman(
        con_args=podman_args,
        img="docker.io/pandoc/typst:latest",
        entry_args=args,
        sp_args=sp_args,
    )

def png2jpg(png_fp):
    return sp.run(
        (
            'gm',
            'convert',
            '-quality',
            '80',
            str(png_fp),
            str(png_fp.with_suffix('.jpg')),
        )
    )


def main():
    # Set working directory
    cd0()

    # Spell check
    cmd = """
        cat ./presentation.typ \
        | podman run --rm --interactive docker.io/pandoc/typst:latest \
             --from typst --to plain \
        | hunspell -l \
        | sort \
        | uniq \
    """
    sp.run(cmd, check=True, shell=True)

    # Compile to PDF
    typst(
        "compile",
        "./presentation.typ",
        "./export.pdf",
    )

    # Exit if only PDF is desired
    if Path(__file__).stem == 'preview':
        sys.exit(0)

    # Compile to PPTX (PowerPoint) and revealjs (HTML)
    with TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        # Compile to PNGs
        typst(
            "compile",
            "--ppi", "300",
            "./presentation.typ",
            str(tmpdir / "img{0p}.png"),
            podman_args=[f'-v={tmpdir}:{tmpdir}'],
        )

        # Convert PNGs to JPEGs
        for j, result in dispatch(
            jobs=tmpdir.glob("*.png"),
            worker=png2jpg,
        ):
            if result.returncode != 0:
                raise Exception(f'error: gm convert failed: {j}')

        # Compile to PPTX
        md_blob = "\n".join([
            # https://pandoc.org/demo/example33/10.8-background-in-reveal.js-beamer-and-pptx.html
            # https://revealjs.com/backgrounds/
            # https://revealjs.com/transitions/
            f"""# {{
                data-background-image="{i}"
                data-background-size="contain"
                data-background-position="center"
                data-background-repeat="no-repeat"
                data-background-opacity="1"
                data-background-color="black"
                data-transition="none"
                data-background-transition="none"
            }}"""
            for i in sorted(list(tmpdir.glob("*.jpg")))
        ])
        pandoc(
            "--from=markdown",
            "--to=pptx",
            "--output=./export.pptx",
            "-",  # Read from stdin
            podman_args=[f"-v={tmpdir}:{tmpdir}"],
            sp_args={"input": md_blob}
        )

        # Compile to revealjs (HTML)
        pandoc(
            "--standalone",
            "--embed-resources",
            "--from=markdown",
            "--to=revealjs",
            "--output=./export.html",
            "-",  # Read from stdin
            podman_args=[f"-v={tmpdir}:{tmpdir}"],
            sp_args={"input": md_blob}
        )

if __name__ == '__main__':
    main()
    sys.exit(0)



# TODO check out https://github.com/polylux-typ/polylux
