#!/bin/python3

import os
import sys
import pwd
import time
import signal
import subprocess as sp
from pathlib import Path


sys.stderr = sys.stdout  # Redirect stderr to stdout


def clear_cg_procs(cg_path):
    # Move all currently running processes out of root of cgroup
    cg_path = Path(cg_path)
    cg_leaf = Path(cg_path / "default")
    cg_leaf.mkdir(exist_ok=True)
    with open(cg_path / "cgroup.procs", 'r') as f:
        pid_list = f.read().strip().splitlines()
    for pid in pid_list:
        try:
            (cg_leaf / "cgroup.procs").write_text(pid)
        except OSError as e:
            if str(e) != "[Errno 22] Invalid argument":
                raise e


def chown_cg(cg_dir, uid, gid):
    # Give ownership of given cgroup to given uid:gid
    cg_dir = Path(cg_dir)
    os.chown(cg_dir, uid, gid)
    os.chown(cg_dir / "cgroup.procs", uid, gid)
    os.chown(cg_dir / "cgroup.threads", uid, gid)
    os.chown(cg_dir / "cgroup.subtree_control", uid, gid)


def get_pid_ruid_euid(pid):
    # Return the real UID and the effective UID for the given PID.
    for i in Path("/proc/", str(pid), "status").read_text().splitlines():
        if i.startswith("Uid:\t"):
            _, ruid, euid, _, _ = i.split('\t')
            return (ruid, euid)


# Make sure user is one we know how to work with
target_uid = 1000  # TODO make this user agnostic (not hardcoded to 'daniel')
assert pwd.getpwuid(target_uid).pw_name == 'daniel'

# If Sway session is already in its own cgroup, mission accomplished
if Path(f"/sys/fs/cgroup/1/user{target_uid}/swaywm/cgroup.controllers").exists():
    print("Sway session already has its own cgroup")
    signal.pause()
    sys.exit(0)

# Setup cgroups hierarchy
clear_cg_procs("/sys/fs/cgroup")
clear_cg_procs("/sys/fs/cgroup/1")
Path(f"/sys/fs/cgroup/1/user{target_uid}").mkdir(exist_ok=True)
chown_cg(f"/sys/fs/cgroup/1/user{target_uid}", target_uid, target_uid)
Path(f"/sys/fs/cgroup/1/user{target_uid}/swaywm").mkdir(exist_ok=True)
for p in (
    "/sys/fs/cgroup/cgroup.subtree_control",
    "/sys/fs/cgroup/1/cgroup.subtree_control",
    f"/sys/fs/cgroup/1/user{target_uid}/cgroup.subtree_control",
):
    with open(p, 'w') as f:
        # NOTE: Each of these must exist in /sys/fs/cgroup/cgroup.controllers,
        # or this will fail
        f.write("+memory +pids +cpu +io")

# Watch for Sway init script, then move it to user controlled cgroup
cmd = (
    'pgrep',
    '-fx',
    '-U', str(target_uid),
    'dash /home/daniel/code/bin/launch-swaywm',
)
while True:
    p = sp.run(cmd, text=True, capture_output=True)
    if (p.returncode == 0) and (p.stdout.strip() != ''):
        result = p.stdout.strip().splitlines()
        assert len(result) == 1
        sway_init_pid = int(result[0])
        break
    time.sleep(0.1)
Path(f"/sys/fs/cgroup/1/user{target_uid}/swaywm/cgroup.procs").write_text(
    str(sway_init_pid)
)

# Service's job is done, so pause (so runit sees this service as "alive")
signal.pause()
