# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc

# CONSTANTS AND ALIASES -------------------------------------------------------

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# FUNCTIONS -------------------------------------------------------------------

# Change shell's working dir to last dir in lf on exit
alias lf='exec ~/code/bin/lfcdsh'
