# Enable italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default).
--italic-text=always

# Never print binary files
--binary=no-printing

# Configure which components to display
--style=header-filename,grid
