[pycodestyle]
# NOTE: If your editor keep highlighting any of the ignored items, you may need
# to also set them to be ignored in other Python linter (flake8, ruff, etc...)
# config files.
#
# "expected x blank lines"
# "module level import not at top of file"
# "line too long"
# "missing whitespace around bitwise or shift operator"
# "missing whitespace around parameter equals"
# "E251 unexpected spaces around keyword / parameter equals"
ignore = E302,E303,E305,E402,E501,E227,E252,E251
