# To modify the system-wide sshd configuration, create a  *.conf  file under
#  /etc/ssh/sshd_config.d/  which will be automatically included.

# This config can be validated by running `sudo sshd -t` and reloaded with
# `sudo systemctl reload sshd.service`

Banner none

PermitRootLogin no

MaxAuthTries 4
LoginGraceTime 32

PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
GSSAPIAuthentication no
KerberosAuthentication no
ChallengeResponseAuthentication no
IgnoreRhosts yes

ClientAliveInterval 256
ClientAliveCountMax 4
