services:
  wishlist:
    container_name: wishlist
    image: ghcr.io/cmintey/wishlist:latest
    ports:
      #TODO
      - 3280:3280
    volumes:
      # TODO
      # Where user image uploads get stored
      - ./uploads:/usr/src/app/uploads
      # Where the sqlite database gets stored
      - ./data:/usr/src/app/data
    environment:
      # TODO
      ORIGIN: http://localhost:3280 # The URL your users will be connecting to
      TOKEN_TIME: 72 # hours until signup and password reset tokens expire
    cap_drop:
      - ALL
    cap_add:
      # https://docs.docker.com/engine/containers/run
      # /#runtime-privilege-and-linux-capabilities
      #
      # Bind a socket to internet domain privileged ports (port numbers
      # less than 1024).
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,mode=1700
    restart: always
    deploy:
      resources:
        limits:
          mem_limit: 256m          # Limit memory to 256MB
          cpus: 0.5                # Limit CPU usage to 50% of a single core
    depends_on:
      - rathole
  rathole:
    image: docker.io/rapiz1/rathole:latest
    volumes:
      # TODO
      - ~/rathole.toml:/rh.toml:ro,U,Z
    command: "/rh.toml"
    cap_drop:
      - ALL
    cap_add:
      # https://docs.docker.com/engine/containers/run
      # /#runtime-privilege-and-linux-capabilities
      #
      # Bind a socket to internet domain privileged ports (port numbers
      # less than 1024).
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,mode=1700
    restart: always
    deploy:
      resources:
        limits:
          mem_limit: 256m          # Limit memory to 256MB
          cpus: 0.5                # Limit CPU usage to 50% of a single core
